In [1]:
import pandas as pd

In [4]:
# Carregamento de Dados.
df_datainsight = pd.read_csv(r'C:\Users\User\Documents\Dados Codigo Certo\insight-basico-python\data\dados.csv', encoding='latin-1', sep=',', low_memory=False)
df_datainsight

,ID,Nome do Curso,Quantidade de Vendas,Preço Unitário,Data
0,1,Introdução à Programação em Python,50,39.9,2023-01-01
1,2,Desenvolvimento Web com HTML e CSS,30,59.9,2023-01-02
2,3,JavaScript Avançado: Frameworks e Bibliotecas,20,79.9,2023-01-03
3,4,Introdução ao Machine Learning,15,99.9,2023-01-04
4,5,Desenvolvimento Mobile com React Native,25,69.9,2023-01-05
5,6,Arquitetura de Microserviços,12,89.9,2023-01-06
6,7,Banco de Dados SQL e NoSQL,18,79.9,2023-01-07
7,8,Segurança da Informação: Fundamentos,10,109.9,2023-01-08
8,9,Cloud Computing com AWS,22,99.9,2023-01-09
9,10,DevOps: Integração e Entrega Contínua,8,119.9,2023-01-10
10,11,Desenvolvimento Web com HTML e CSS,20,59.9,2023-01-11
11,12,JavaScript Avançado: Frameworks e Bibliotecas,15,79.9,2023-01-12
12,13,Introdução ao Machine Learning,10,99.9,2023-01-13
13,14,Desenvolvimento Mobile com React Native,18,69.9,2023-01-14
14,15,Arquitetura de Microserviços,8,89.9,2023-01-15
15,16,Banco de Dados SQL e NoSQL,12,79.9,2023-01-16
16,17,Segurança da Informação: Fundamentos,5,109.9,2023-01-17
17,18,Cloud Computing com AWS,15,99.9,2023-01-18
18,19,DevOps: Integração e Entrega Contínua,6,119.9,2023-01-19
19,20,Introdução à Programação em Python,45,39.9,2023-01-20
20,21,Desenvolvimento Web com HTML e CSS,25,59.9,2023-01-21
21,22,JavaScript Avançado: Frameworks e Bibliotecas,18,79.9,2023-01-22
22,23,Introdução ao Machine Learning,12,99.9,2023-01-23
23,24,Desenvolvimento Mobile com React Native,20,69.9,2023-01-24
24,25,Arquitetura de Microserviços,10,89.9,2023-01-25

In [5]:
# Esibindo dados esstatisticos basicos
df_datainsight.describe()

              ID  Quantidade de Vendas  Preço Unitário
count  25.000000             25.000000       25.000000
mean   13.000000             17.960000       83.900000
std     7.359801             10.921996       21.984843
min     1.000000              5.000000       39.900000
25%     7.000000             10.000000       69.900000
50%    13.000000             15.000000       79.900000
75%    19.000000             20.000000       99.900000
max    25.000000             50.000000      119.900000

In [8]:
# Exibindo estatisticas da coluna Preço de venda

# Exibir a média
mean_values = df_datainsight['Preço Unitário'].mean()

# Exibir a mediana
median_values = df_datainsight['Preço Unitário'].median()

# Exibir mínimo e máximo manualmente
min_values = df_datainsight['Preço Unitário'].min()
max_values = df_datainsight['Preço Unitário'].max()

# Exibir desvio padrão
std_dev = df_datainsight['Preço Unitário'].std()

print(f'Media dos preços do curso: {mean_values} ')
print(f'Mediana dos preços do curso: {median_values} ')
print(f'Valor minimo do curso: {min_values} ')
print(f'Valor máximo do curso: {max_values} ')
print(f'Desvio padrão dos preços: {std_dev} ')

Media dos preços do curso: 83.90000000000002
Mediana dos preços do curso: 79.9
Valor minimo do curso: 39.9
Valor máximo do curso: 119.9
Desvio padrão dos preços: 21.984843263788203

In [9]:
#Exibindo estatisticas da coluna Quantidade vendida

# Exibir a média
mean_values = df_datainsight['Quantidade de Vendas'].mean()

# Exibir a mediana
median_values = df_datainsight['Quantidade de Vendas'].median()

# Exibir mínimo e máximo manualmente
min_values = df_datainsight['Quantidade de Vendas'].min()
max_values = df_datainsight['Quantidade de Vendas'].max()

# Exibir desvio padrão
std_dev = df_datainsight['Quantidade de Vendas'].std()

print(f'Quantidade media do curso: {mean_values} ')
print(f'Mediana do curso: {median_values} ')
print(f'Quantidade minima do curso: {min_values} ')
print(f'Quantidade máxima do curso: {max_values} ')
print(f'Desvio padrão da quantidade: {std_dev} ')

Quantidade media do curso: 17.96
Mediana do curso: 15.0
Quantidade minima do curso: 5
Quantidade máxima do curso: 50
Desvio padrão da quantidade: 10.921996154549772

In [10]:
# Calcular a receita total gerada pela venda dos cursos.

df_qtd_vendas = df_datainsight['Quantidade de Vendas'].sum()
df_qtd_unit = df_datainsight['Preço Unitário'].sum()

df_receita = df_qtd_vendas * df_qtd_unit


print(f'Receita TOTAL das vendas: R$ {df_receita:.2f}')

Receita TOTAL das vendas: R$ 941777.50

In [11]:
# Identificar o curso com o maior número de vendas.

indice_max = df_datainsight['Quantidade de Vendas'].idxmax()


nome_max = df_datainsight.loc[indice_max, 'Nome do Curso']
vendas_max = df_datainsight.loc[indice_max, 'Quantidade de Vendas']

print(f'O curso: {nome_max}, teve {vendas_max} vendas no periodo.')

O curso: Introdução à Programação em Python, teve 50 vendas no periodo